config/routes.rb
Rails.application.routes.draw do

  resources :contacts
  root 'static_pages#welcome'

  get 'about-us',                                     to: 'static_pages#aboutUs'
  get 'about-us/our-philosophy',                      to: 'static_pages#ourPhilosophy'
  get 'about-us/builders-story',                      to: 'static_pages#buildersStory'
  get 'about-us/accolades',                           to: 'static_pages#accolades'

  get 'inspiration',                                  to: 'static_pages#gallery01'

  get 'design-and-build',                             to: 'static_pages#designAndBuild'
  get 'design-and-build/building-process',            to: 'static_pages#buildingProcess'

  get 'design-and-build/series',                      to: 'static_pages#series'
  get 'design-and-build/series/premier',              to: 'static_pages#premierSeries'
  get 'design-and-build/series/classic',              to: 'static_pages#classicSeries'
  get 'design-and-build/series/lago',                 to: 'static_pages#lagoSeries'
  get 'design-and-build/series/signature',            to: 'static_pages#signatureSeries'

  get 'design-and-build/neighborhoods',               to: 'static_pages#neighborhoods'
  get 'design-and-build/frequently-asked-questions',  to: 'static_pages#frequentlyAskedQuestions'

  get 'our-warranty',                                 to: 'static_pages#warranty'
  get 'contact-us',                                   to: 'contacts#new'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        ContactUsMailer.contactUsSend(@contact).deliver_now
        format.html { redirect_to @contact, notice: 'Your message was successfully sent. A company representative will be contacting you within 24 hours.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :comments)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def welcome
  end

  def aboutUs
  end

    def ourPhilosophy
    end

    def buildersStory
    end

    def accolades
    end

  def inspiration
  end

    def gallery01
    end

    def gallery02
    end

    def gallery03
    end

    def gallery04
    end

  def designAndBuild
  end

    def buildingProcess
    end

    def series
    end

      def premierSeries
      end

      def classicSeries
      end

      def lagoSeries
      end

      def signatureSeries
      end

    def neighborhoods
    end

    def frequentlyAskedQuestions
    end

  def warranty
  end

  def contactUs
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contacts/_form.html.erb
<%= form_for(contact) do |f| %>

  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="column">
      <div class="field">
        <%= f.label :name, class:'hide' %>
        <%= f.text_field :name, required: 'true', placeholder:'Name' %>
      </div>
    </div>
    <div class="column">
      <div class="field">
        <%= f.label :email, class:'hide' %>
        <%= email_field('contact', 'email', required: 'true', placeholder:'Email') %>
      </div>
    </div>
  </div>

  <div class="field">
    <%= f.label :comments, class:'hide' %>
    <%= f.text_area :comments, required: 'true', placeholder:'Message' %>
  </div>

  <div class="actions">
    <%= f.submit("SEND", id:"submit", onclick:"return verifyHuman($('#spamChecker').val());") %>
  </div>

  <input type="hidden" name="spamChecker" id="spamChecker" value="" />

<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.comments %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<section class="contactUs">

  <div class="mobile">
    <div id="contactUsBox01" class="imgBox"></div>
    <div class="content">
      <h1>CONTACT US</h1>
      <h3>LIVE OAK CUSTOM HOMES</h3>
      <p>
        <strong>
          6838 Greenwood Dr.<br />
          Corpus Christi, TX 78415
        </strong>
      </p>
      <p>
        Office: <a href="tel:3618541626">(361) 854-1626</a><br />
        General Sales: <a href="tel:3618509153">(361) 850-9153</a><br />
        Fax: (866) 408-0656</a>
      </p>
      <p>
        <a href="#">Download Broker-Client Registration Form</a>
      </p>
    </div>

    <%= render 'form', contact: @contact %>

    <div class="content">
      <h5>Contact our Corpus Christi Live Oak Construction salespersons directly.</h5>

      <h3>Shoreline Oaks</h3>
      <p>
        <strong>Gloria Martinez</strong><br />
        Sales Representative<br />
        <a href="mailto:gloria@liveoakcustomhomes.com">gloria@liveoakcustomhomes.com</a><br />
        2117 Oak Creek Cove<br />
        Office: <a href="tel:3619375668">(361) 937-5668</a><br />
        Cell: <a href="tel:3615491432">(361) 549-1432</a><br />
      </p>

      <h3>THE COVES AT LAGO VISTA</h3>
      <p>
        <strong>Casey Mengele</strong><br />
        Sales Representative<br />
        <a href="mailto:casey@liveoakcustomhomes.com">casey@liveoakcustomhomes.com</a><br />
        5901 S. Oso Pkwy<br />
        Office: <a href="tel:3618509153">(361) 850-9153</a>
      </p>
    </div>

    <div id="contactUsBox02" class="imgBox"></div>
  </div>

  <div class="tablet">
    <div class="row">
      <div class="column">
        <div class="content">
          <h1>CONTACT US</h1>
          <h3>LIVE OAK CUSTOM HOMES</h3>
          <p>
            <strong>
              6838 Greenwood Dr.<br />
              Corpus Christi, TX 78415
            </strong>
          </p>
          <p>
            Office: <a href="tel:3618541626">(361) 854-1626</a><br />
            General Sales: <a href="tel:3618509153">(361) 850-9153</a><br />
            Fax: (866) 408-0656</a>
          </p>
          <p>
            <a href="#">Download Broker-Client Registration Form</a>
          </p>
        </div>
      </div>
      <div class="column">
        <%= render 'form', contact: @contact %>
      </div>
    </div>
    <div class="row">
      <div class="column">
        <div id="contactUsBox01" class="imgBox"></div>
      </div>
      <div class="column">
        <div id="contactUsBox02" class="imgBox"></div>
      </div>
    </div>
  </div>

  <div class="desktop">
    <div class="row">
      <div id="contactUsBox01" class="column bg-img">
        <h1 class="page-header">SAY HELLO</h1>
      </div>
    </div>
    <div class="row">
      <div class="column column-10"></div>
      <div class="column column-40">
        <div class="content-small">
          <h1>CONTACT US:</h1>
          <p>
            <a href="#">Download Broker-Client Registration Form</a>
          </p>
          <div class="row">
            <div class="column">
              <h5>VISIT US:</h5>
              <p>
                Live Oak Custom Homes<br>
                6838 Greenwood Dr.<br />
                Corpus Christi, TX 78415
              </p>
            </div>
            <div class="column">
              <h5>CALL US:</h5>
              <p>
                Office: <a href="tel:3618541626">(361) 854-1626</a><br />
                General Sales: <a href="tel:3618509153">(361) 850-9153</a><br />
                Fax: (866) 408-0656</a>
              </p>
            </div>
          </div>
        </div>
      </div>
      <div class="column column-40">
        <div class="content-small">
          <h1>EMAIL US:</h1>
          <%= render 'form', contact: @contact %>
        </div>
      </div>
      <div class="column column-10"></div>
    </div>
    <div class="row">
      <div id="map"></div>
    </div>
  </div>

</section>

app/views/contacts/show.html.erb
<section>
  <div class="content">

    <h1>MESSAGE SENT</h1>

    <p id="notice"><%= notice %></p>

    <p>
      <strong>Name:</strong>
      <%= @contact.name %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @contact.email %>
    </p>

    <p>
      <strong>Comments:</strong>
      <%= @contact.comments %>
    </p>

    <%= link_to 'Send Another Message', new_contact_path %>

  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Live Oak Custom Homes - Find Your Neighborhood, Build Your Home</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="We provide our customers with a full service custom home design experience. We minimize the frustration involved in a traditional building experience and focus on your family's home.">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/milligram/1.3.0/milligram.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-21324105-2']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>

    <%= render "shared/header" %>
    <%= yield %>

    <footer>
      <div class="menu">
        <%= link_to "HOME", root_path %> <span>|</span>
        <%= link_to "ABOUT US", about_us_path %> <span>|</span>
        <%= link_to "INSPIRATION", inspiration_path %> <span>|</span>
        <%= link_to "DESIGN & BUILD", design_and_build_path %> <span>|</span>
        <%= link_to "OUR WARRANTY", our_warranty_path %> <span>|</span>
        <%= link_to "CONTACT US", contact_us_path %>
      </div>
      <div class="copyright">
        Copyright 2017 Live Oak Construction, Inc. All Rights Reserved.
      </div>
    </footer>

    <script src="https://use.fontawesome.com/3fcb9a3989.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAAnCY4dBCwsd_27_g7N-M76vIIWWYzOJg&callback=loadMap" async defer></script>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_header.html.erb
<header>

  <div id="logo">
    <a href="/"><%= image_tag "Live-Oak-Custom-Homes-logo.png" %></a>
  </div>

  <nav>
    <a href="#" onclick="$('nav .menu').toggle();" id="mobileBtn"><i class="fa fa-bars" aria-hidden="true"></i></a>
    <%= render "shared/menu" %>
  </nav>

</header>

app/views/shared/_menu.html.erb
<div class="menu">
  <%= link_to "HOME", root_path %> <span>|</span>

  <a href="#" onClick="showSubMenu('aboutSubMenu');" onMouseOver="showSubMenu('aboutSubMenu');">ABOUT US <i class="fa fa-chevron-down" aria-hidden="true"></i></a> <span>|</span>
  <div id="aboutSubMenu" class="sub-menu">
    <%= link_to "Our Philosophy", about_us_our_philosophy_path %> <span>|</span>
    <%= link_to "Builder's Story", about_us_builders_story_path %> <span>|</span>
    <%= link_to "Accolades", about_us_accolades_path %>
  </div>

  <%= link_to "INSPIRATION", inspiration_path %> <span>|</span>

  <a href="#" onClick="showSubMenu('designAndBuildSubMenu');" onMouseOver="showSubMenu('designAndBuildSubMenu');">DESIGN &amp; BUILD <i class="fa fa-chevron-down" aria-hidden="true"></i></a> <span>|</span>
  <div id="designAndBuildSubMenu" class="sub-menu">
    <%= link_to "Building Process", design_and_build_building_process_path %> <span>|</span>
    <%= link_to "Series", design_and_build_series_path %> <span>|</span>
    <%= link_to "Neighborhoods", design_and_build_neighborhoods_path %> <span>|</span>
    <%= link_to "Frequently Asked Questions", design_and_build_frequently_asked_questions_path %>
  </div>

  <%= link_to "OUR WARRANTY", our_warranty_path %> <span>|</span>
  <%= link_to "CONTACT US", new_contact_path %>
</div>

app/views/static_pages/aboutUs.html.erb
<div class="mobile">
  <div class="container blackBoxGrid">

    <div class="row">
      <div class="column aboutPhilosophy">
        <a href="/about-us/our-philosophy">
          <h1>OUR PHILOSOPHY</h1>
          <p>Live Oak Construction understands the true meaning of home. It is more than just an address, it is where you live and experience intimate moments amongst family and friends...</p>
        </a>
      </div>
      <div class="column buildersStory">
        <a href="/about-us/builders-story">
          <h1>BUILDER'S STORY</h1>
          <p>Live Oak Construction Inc. was created in April of 1991 by Ronald A. Voss, a licensed professional engineer in the state of Texas...</p>
        </a>
      </div>
    </div>

    <div class="row">
      <div class="column accolades">
        <a href="/about-us/accolades">
          <h1>ACCOLADES</h1>
          <p>A collection of our various awards and testomonials from companies and customers alike that had something to say about our work...</p>
        </a>
      </div>
    </div>

  </div>
</div>
<div class="desktop">
  <div class="blackBoxGrid">

    <div class="row">
      <div class="column aboutPhilosophy">
        <a href="/about-us/our-philosophy">
          <h1>OUR PHILOSOPHY</h1>
          <p>Live Oak Construction understands the true meaning of home. It is more than just an address, it is where you live and experience intimate moments amongst family and friends...</p>
        </a>
      </div>
      <div class="column buildersStory">
        <a href="/about-us/builders-story">
          <h1>BUILDER'S STORY</h1>
          <p>Live Oak Construction Inc. was created in April of 1991 by Ronald A. Voss, a licensed professional engineer in the state of Texas...</p>
        </a>
      </div>
    </div>

    <div class="row">
      <div class="column accolades">
        <a href="/about-us/accolades">
          <h1>ACCOLADES</h1>
          <p>A collection of our various awards and testomonials from companies and customers alike that had something to say about our work...</p>
        </a>
      </div>
    </div>

  </div>
</div>

app/views/static_pages/designAndBuild.html.erb
<div class="mobile">
  <div class="container blackBoxGrid">

    <div class="row">
      <div class="column buildingProcess">
        <a href="/design-and-build/building-process">
          <h1>BUILDING PROCESS</h1>
          <p>We pride ourselves on providing our customers with a full service custom home design experience. Learn about how the process works from start to finish so you can know what to expect when building a Live Oak Home...</p>
        </a>
      </div>
      <div class="column series">
        <a href="/design-and-build/series">
          <h1>SERIES</h1>
          <p>Live Oak Homes offers home builders three series to choose from.</p>
          <p>Each series offers different levels of features and amenities to provide home owners with versatilitby and accommodate individual needs...</p>
        </a>
      </div>
    </div>

    <div class="row">
      <div class="column neighborhoods">
        <a href="/design-and-build/neighborhoods">
          <h1>NEIGHBORHOODS</h1>
          <p>Shoreline Oaks and the Coves at Lago Vista are both beautiful communities of Live Oak Homes with many ammenities afforded to those who live there. Learn about each community, view neighborhood plats, and schedule an appointment to view model homes...</p>
        </a>
      </div>
      <div class="column faq">
        <a href="/design-and-build/frequently-asked-questions">
          <h1>FREQUENTLY ASKED QUESTIONS</h1>
          <p>Read commonly asked questions and find answers about Live Oak homes, neighborhoods, the building process and more...</p>
        </a>
      </div>
    </div>

  </div>
</div>
<div class="desktop">
  <div class="blackBoxGrid">

    <div class="row">
      <div class="column buildingProcess">
        <a href="/design-and-build/building-process">
          <h1>BUILDING PROCESS</h1>
          <p>We pride ourselves on providing our customers with a full service custom home design experience. Learn about how the process works from start to finish so you can know what to expect when building a Live Oak Home...</p>
        </a>
      </div>
      <div class="column series">
        <a href="/design-and-build/series">
          <h1>SERIES</h1>
          <p>Live Oak Homes offers home builders three series to choose from.</p>
          <p>Each series offers different levels of features and amenities to provide home owners with versatilitby and accommodate individual needs...</p>
        </a>
      </div>
    </div>

    <div class="row">
      <div class="column neighborhoods">
        <a href="/design-and-build/neighborhoods">
          <h1>NEIGHBORHOODS</h1>
          <p>Shoreline Oaks and the Coves at Lago Vista are both beautiful communities of Live Oak Homes with many ammenities afforded to those who live there. Learn about each community, view neighborhood plats, and schedule an appointment to view model homes...</p>
        </a>
      </div>
      <div class="column faq">
        <a href="/design-and-build/frequently-asked-questions">
          <h1>FREQUENTLY ASKED QUESTIONS</h1>
          <p>Read commonly asked questions and find answers about Live Oak homes, neighborhoods, the building process and more...</p>
        </a>
      </div>
    </div>

  </div>
</div>

app/views/static_pages/frequentlyAskedQuestions.html.erb
<section>
  <div class="content">
    <div class="row">
      <div class="column">
        <h1>FREQUENTLY ASKED QUESTIONS</h1>
      </div>
    </div>

    <div class="row">
      <div class="column">
        <ul>
          <li>
            Are you a member of the Better Business Bureau? Yes, we are a member of the BBB in good standing.<br />
            <%= link_to "READ MORE about the Live Oak Philosophy", about_us_our_philosophy_path %>
          </li>
          <li>
            We have a home to sell; can you build on a contingency? Yes, we offer a resale program that, in most cases, allows you to begin building your new home while we list and market your current home.
          </li>
          <li>
            Do I need to have my own plans before we begin? No, part of our full service design to build program includes designing your own floor plan unique to your specific needs and lifestyle.<br />
            <%= link_to "READ MORE about our Building Process", design_and_build_building_process_path %>
          </li>
          <li>
            We don't own a lot? Do we need our own land/home site before we start this process? Our qualified staff can assist you in finding the perfect home site in the neighborhood or community that meets your criteria.<br />
            <%= link_to "TAKE A LOOK at the Live Oak Neighborhoods", design_and_build_neighborhoods_path %>
          </li>
          <li>
            What price ranges do you build in? We are a full custom builder, what you can imagine we can bring to life. We have built homes ranging from $100,000 to $2,500,000 so anything is possible.
          </li>
        </ul>
      </div>
      <div class="column">
        <ul>
          <li>
            Do we need to obtain our own financing during the building process? No, we have relationships with numerous local banks where we can obtain interim financing for your project.<br />
            <%= link_to "READ MORE about our Building Process", design_and_build_building_process_path %>
          </li>
          <li>
            About how long does it take to build a new home? Typically the building process takes between 4 -8 months dependent on size.<br />
            <%= link_to "READ MORE about our Building Process", design_and_build_building_process_path %>
          </li>
          <li>
            Will you work with my realtor? Yes, Live Oak has wonderful relationships with numerous local realtors and is happy to have them be a part of your project.
          </li>
          <li>
            How do we begin the process? Contact our custom home sales department at (361) 850-9153 to set up your initial meeting.<br />
            <%= link_to "MORE DETAILS for getting in touch with us", new_contact_path %>
          </li>
        </ul>
      </div>
    </div>

  </div>

  <div class="row">
    <div class="column">
      <div id="faqBox01" class="imgBox"></div>
    </div>
    <div class="column">
      <div id="faqBox02" class="imgBox"></div>
    </div>
    <div class="column">
      <div id="faqBox03" class="imgBox"></div>
    </div>
  </div>
</section>

app/views/static_pages/inspiration.html.erb
<div class="mobile">
  <div class="container blackBoxGrid">

    <div class="row">
      <div class="column gallery01">
        <a href="/inspiration/gallery-01">
          <h1>EXAMPLE HOME ONE</h1>
          <p>This is placeholder text that will be two short sentences describing the home featured on this splash page.</p>
        </a>
      </div>
      <div class="column gallery02">
        <a href="/inspiration/gallery-02">
          <h1>EXAMPLE HOME TWO</h1>
          <p>This is placeholder text that will be two short sentences describing the home featured on this splash page.</p>
        </a>
      </div>
    </div>

    <div class="row">
      <div class="column gallery03">
        <a href="/inspiration/gallery-03">
          <h1>EXAMPLE HOME THREE</h1>
          <p>This is placeholder text that will be two short sentences describing the home featured on this splash page.</p>
        </a>
      </div>
      <div class="column gallery04">
        <a href="/inspiration/gallery-04">
          <h1>EXAMPLE HOME FOUR</h1>
          <p>This is placeholder text that will be two short sentences describing the home featured on this splash page.</p>
        </a>
      </div>
    </div>

  </div>
</div>
<div class="tablet">
  <div class="blackBoxGrid">

    <div class="row">
      <div class="column gallery01">
        <a href="/inspiration/gallery-01">
          <h1>EXAMPLE HOME ONE</h1>
          <p>This is placeholder text that will be two short sentences describing the home featured on this splash page.</p>
        </a>
      </div>
      <div class="column gallery02">
        <a href="/inspiration/gallery-02">
          <h1>EXAMPLE HOME TWO</h1>
          <p>This is placeholder text that will be two short sentences describing the home featured on this splash page.</p>
        </a>
      </div>
    </div>

    <div class="row">
      <div class="column gallery03">
        <a href="/inspiration/gallery-03">
          <h1>EXAMPLE HOME THREE</h1>
          <p>This is placeholder text that will be two short sentences describing the home featured on this splash page.</p>
        </a>
      </div>
      <div class="column gallery04">
        <a href="/inspiration/gallery-04">
          <h1>EXAMPLE HOME FOUR</h1>
          <p>This is placeholder text that will be two short sentences describing the home featured on this splash page.</p>
        </a>
      </div>
    </div>

  </div>
</div>
<div class="desktop">
  <div class="blackBoxGrid">

    <div class="row">
      <div class="column gallery01">
        <a href="/inspiration/gallery-01">
          <h1>EXAMPLE HOME ONE</h1>
          <p>This is placeholder text that will be two short sentences describing the home featured on this splash page.</p>
        </a>
      </div>
      <div class="column gallery02">
        <a href="/inspiration/gallery-02">
          <h1>EXAMPLE HOME TWO</h1>
          <p>This is placeholder text that will be two short sentences describing the home featured on this splash page.</p>
        </a>
      </div>
    </div>

    <div class="row">
      <div class="column gallery03">
        <a href="/inspiration/gallery-03">
          <h1>EXAMPLE HOME THREE</h1>
          <p>This is placeholder text that will be two short sentences describing the home featured on this splash page.</p>
        </a>
      </div>
      <div class="column gallery04">
        <a href="/inspiration/gallery-04">
          <h1>EXAMPLE HOME FOUR</h1>
          <p>This is placeholder text that will be two short sentences describing the home featured on this splash page.</p>
        </a>
      </div>
    </div>

  </div>
</div>

app/views/static_pages/ourPhilosophy.html.erb
<section class="ourPhilosophy">

  <div class="mobile">
    <div id="ourPhilosophyBox01" class="imgBox"></div>
    <div class="content">
      <h1>OUR PHILOSOPHY</h1>
      <p>Live Oak Construction understands the true meaning of home. It is more than just an address, it is where you live and experience intimate moments amongst family and friends.</p>
      <p>With over 20 years of experience we know that to truly be successful we must capture your personal vision and design a home that both reflects your personality and enhances your lifestyle.</p>
      <p>Our commitment to you goes well beyond a contract. It is in providing you with constant support, attention to detail and incomparable customer service throughout your building experience. Our exceptional quality and outstanding craftsmanship ensure your dreams become a reality in a Live Oak Construction Custom Home built for a lifetime.</p>
    </div>
  </div>

  <div class="tablet">

    <div class="row">
      <div class="column column-33">
        <div id="ourPhilosophyBox01" class="imgBox"></div>
      </div>
      <div class="column column-67">
        <div class="content" style="margin:10px 20px;">
          <h1>OUR PHILOSOPHY</h1>
          <p>Live Oak Construction understands the true meaning of home. It is more than just an address, it is where you live and experience intimate moments amongst family and friends.</p>
          <p>With over 20 years of experience we know that to truly be successful we must capture your personal vision and design a home that both reflects your personality and enhances your lifestyle.</p>
          <p>Our commitment to you goes well beyond a contract. It is in providing you with constant support, attention to detail and incomparable customer service throughout your building experience. Our exceptional quality and outstanding craftsmanship ensure your dreams become a reality in a Live Oak Construction Custom Home built for a lifetime.</p>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="column">
        <div id="ourPhilosophyBox02" class="imgBox"></div>
      </div>
    </div>

  </div>

  <div class="desktop">

    <div class="row">
      <div id="ourPhilosophyBox01" class="column column-67 bg-img"></div>
      <div class="column column-33">
        <div class="content">
          <h1>OUR PHILOSOPHY</h1>
          <p>Live Oak Construction understands the true meaning of home. It is more than just an address, it is where you live and experience intimate moments amongst family and friends.</p>
          <p>With over 20 years of experience we know that to truly be successful we must capture your personal vision and design a home that both reflects your personality and enhances your lifestyle.</p>
          <p>Our commitment to you goes well beyond a contract. It is in providing you with constant support, attention to detail and incomparable customer service throughout your building experience. Our exceptional quality and outstanding craftsmanship ensure your dreams become a reality in a Live Oak Construction Custom Home built for a lifetime.</p>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="column">
        <div id="ourPhilosophyBox02" class="imgBox"></div>
      </div>
    </div>

  </div>

</section>

app/views/welcome/index.html.erb
<h1>Hello World!</h1>